{% set name = "sfml" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SFML/SFML/archive/{{ version }}.tar.gz
  sha256: f99f71bb2f2608835b1a37e078512b75dd39d52b89e13e12246603a950da3c1f

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('sfml', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}        # [linux]
    - xorg-libx11                    # [linux]
    - xorg-libxrandr                 # [linux]
    - xorg-libxcursor                # [linux]
    - libogg
    - libflac
    - libvorbis
    - openal-soft
    - cmake
    - ninja
    - pkg-config
  host:
    - xorg-xorgproto                 # [linux]
    - xorg-libxext                   # [linux]
    - xorg-libxrender                # [linux]    
    - xorg-libxfixes                 # [linux]
    - xorg-libx11                    # [linux]
    - xorg-libxrandr                 # [linux]
    - xorg-libxcursor                # [linux]
    - xorg-libxi                     # [linux]
    - libogg
    - freetype
    - libflac
    - libvorbis
    - openal-soft
    - libudev                        # [linux]
  run:
    - xorg-libx11                    # [linux]
    - xorg-libxrandr                 # [linux]
    - xorg-libxcursor                # [linux]
    - libogg
    - libfreetype
    - libflac
    - libvorbis
    - openal-soft

test:
  commands:
    - test -f $PREFIX/lib/libsfml-system${SHLIB_EXT}                                # [unix]
    - test -f $PREFIX/lib/libsfml-window${SHLIB_EXT}                                # [unix]
    - test -f $PREFIX/lib/libsfml-network${SHLIB_EXT}                               # [unix]
    - test -f $PREFIX/lib/libsfml-graphics${SHLIB_EXT}                              # [unix]
    - test -f $PREFIX/lib/libsfml-audio${SHLIB_EXT}                                 # [unix]
    - test -f ${PREFIX}/lib/cmake/SFML/SFMLConfig.cmake                             # [unix]
    - test -d ${PREFIX}/include/SFML/Audio                                          # [unix]
    - test -d ${PREFIX}/include/SFML/Graphics                                       # [unix]
    - test -d ${PREFIX}/include/SFML/Network                                        # [unix]
    - test -d ${PREFIX}/include/SFML/System                                         # [unix]
    - test -d ${PREFIX}/include/SFML/Window                                         # [unix]
    - if not exist %LIBRARY_LIB%\\sfml-system.lib exit 1                            # [win]
    - if not exist %LIBRARY_LIB%\\sfml-main.lib exit 1                              # [win]
    - if not exist %LIBRARY_LIB%\\sfml-window.lib exit 1                            # [win]
    - if not exist %LIBRARY_LIB%\\sfml-network.lib exit 1                           # [win]
    - if not exist %LIBRARY_LIB%\\sfml-graphics.lib exit 1                          # [win]
    - if not exist %LIBRARY_LIB%\\sfml-audio.lib exit 1                             # [win]
    - if not exist %LIBRARY_BIN%\\sfml-system-3.dll exit 1                          # [win]
    - if not exist %LIBRARY_BIN%\\sfml-window-3.dll exit 1                          # [win]
    - if not exist %LIBRARY_BIN%\\sfml-network-3.dll exit 1                         # [win]
    - if not exist %LIBRARY_BIN%\\sfml-graphics-3.dll exit 1                        # [win]
    - if not exist %LIBRARY_BIN%\\sfml-audio-3.dll exit 1                           # [win]
    - if exist %LIBRARY_LIB%\\cmake\\SFML\\SFMLConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_INC%\\SFML\\Audio (exit 0) else (exit 1)                    # [win]
    - if exist %LIBRARY_INC%\\SFML\\Graphics (exit 0) else (exit 1)                 # [win]
    - if exist %LIBRARY_INC%\\SFML\\Network (exit 0) else (exit 1)                  # [win]
    - if exist %LIBRARY_INC%\\SFML\\System (exit 0) else (exit 1)                   # [win]
    - if exist %LIBRARY_INC%\\SFML\\Window (exit 0) else (exit 1)                   # [win]

about:
  home: https://github.com/SFML/SFML
  license: Zlib
  license_file: license.md
  summary: 'Simple and Fast Multimedia Library'
  description: |
    SFML is a simple, fast, cross-platform and object-oriented multimedia
    API. It  provides access to windowing, graphics, audio and network. It
    is written in C++,  and has bindings for various languages such as C,
    .Net, Ruby, Python.
  doc_url: https://www.sfml-dev.org
  dev_url: https://github.com/SFML/SFML

extra:
  recipe-maintainers:
    - RaulPPelaez
    - cNoNim
    - martinRenou
